{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12438664","self":"https://issues.apache.org/jira/rest/api/2/issue/12438664","key":"HDFS-721","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310942","id":"12310942","key":"HDFS","name":"Hadoop HDFS","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310942&avatarId=10094","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310942&avatarId=10094","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310942&avatarId=10094","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310942&avatarId=10094"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10292","id":"10292","description":"Scalable Distributed Computing","name":"Hadoop"}},"fixVersions":[],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/3","id":"3","description":"The problem is a duplicate of an existing issue.","name":"Duplicate"},"customfield_12312322":null,"customfield_12310220":"2009-10-21T20:40:00.560+0000","customfield_12312520":null,"customfield_12312323":null,"customfield_12312521":"Tue Jul 29 19:01:40 UTC 2014","customfield_12310420":"16261","customfield_12312320":null,"customfield_12310222":"1_*:*_1_*:*_55286596_*|*_5_*:*_2_*:*_11567300_*|*_4_*:*_1_*:*_150488443039","customfield_12312321":null,"resolutiondate":"2014-07-29T19:01:40.198+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312923":null,"customfield_12312326":null,"customfield_12312920":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312921":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HDFS-721/watchers","watchCount":3,"isWatching":false},"created":"2009-10-21T06:06:43.317+0000","customfield_12310192":null,"customfield_12310191":null,"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12310230":null,"customfield_12312334":null,"customfield_12313422":"false","customfield_12310310":"0.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12311120":null,"customfield_12312330":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12314046","id":"12314046","description":"","name":"0.21.0","archived":false,"released":true,"releaseDate":"2010-08-23"}],"issuelinks":[{"id":"12392839","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12392839","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"inwardIssue":{"id":"12702306","key":"HDFS-6123","self":"https://issues.apache.org/jira/rest/api/2/issue/12702306","fields":{"summary":"Improve datanode error messages","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.svg","name":"Minor","id":"4"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/4","id":"4","description":"An improvement or enhancement to an existing feature or task.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21140&avatarType=issuetype","name":"Improvement","subtask":false,"avatarId":21140}}}}],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2014-07-29T19:01:40.229+0000","customfield_12312335":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/5","description":"A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/resolved.png","name":"Resolved","id":"5","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[],"timeoriginalestimate":null,"description":"Running some loading tests against hdfs branch-0.21 I got the following:\n\n{code}\n2009-10-21 04:57:10,770 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: Receiving block blk_6345892463926159834_1030 src: /XX.XX.XX.141:53112 dest: /XX.XX.XX.140:51010\n2009-10-21 04:57:10,771 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: writeBlock blk_6345892463926159834_1030 received exception org.apache.hadoop.hdfs.server.datanode.ReplicaAlreadyExistsException: Block blk_6345892463926159834_1030 already exists in state RBW and thus cannot be created.\n2009-10-21 04:57:10,771 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: DatanodeRegistration(XX.XX.XX.140:51010, storageID=DS-1292310101-XX.XX.XX.140-51010-1256100924816, infoPort=51075, ipcPort=51020):DataXceiver\norg.apache.hadoop.hdfs.server.datanode.ReplicaAlreadyExistsException: Block blk_6345892463926159834_1030 already exists in state RBW and thus cannot be created.\n    at org.apache.hadoop.hdfs.server.datanode.FSDataset.createTemporary(FSDataset.java:1324)\n    at org.apache.hadoop.hdfs.server.datanode.BlockReceiver.<init>(BlockReceiver.java:98)\n    at org.apache.hadoop.hdfs.server.datanode.DataXceiver.opWriteBlock(DataXceiver.java:258)\n    at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$Receiver.opWriteBlock(DataTransferProtocol.java:382)\n    at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$Receiver.processOp(DataTransferProtocol.java:323)\n    at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:111)\n    at java.lang.Thread.run(Thread.java:619)\n{code}\n\nOn the sender side:\n\n{code}\n2009-10-21 04:57:10,740 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: DatanodeRegistration(XX.XX.XX.141:51010, storageID=DS-1870884070-XX.XX.XX.141-51010-1256100925196, infoPort=51075, ipcPort=51020) Starting thread to transfer block blk_6345892463926159834_1030 to XX.XX.XX.140:51010\n2009-10-21 04:57:10,770 WARN org.apache.hadoop.hdfs.server.datanode.DataNode: DatanodeRegistration(XX.XX.XX.141:51010, storageID=DS-1870884070-XX.XX.XX.141-51010-1256100925196, infoPort=51075, ipcPort=51020):Failed to transfer blk_6345892463926159834_1030 to XX.XX.XX.140:51010 got java.net.SocketException: Original Exception : java.io.IOException: Connection reset by peer\n    at sun.nio.ch.FileChannelImpl.transferTo0(Native Method)\n    at sun.nio.ch.FileChannelImpl.transferToDirectly(FileChannelImpl.java:415)\n    at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:516)\n    at org.apache.hadoop.net.SocketOutputStream.transferToFully(SocketOutputStream.java:199)\n    at org.apache.hadoop.hdfs.server.datanode.BlockSender.sendChunks(BlockSender.java:346)\n    at org.apache.hadoop.hdfs.server.datanode.BlockSender.sendBlock(BlockSender.java:434)\n    at org.apache.hadoop.hdfs.server.datanode.DataNode$DataTransfer.run(DataNode.java:1262)\n    at java.lang.Thread.run(Thread.java:619)\nCaused by: java.io.IOException: Connection reset by peer\n    ... 8 more\n{code}\n\nThe block sequence number, 1030, is one more than that in issue HDFS-720 (same test run but about 8 seconds between errors.","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12312023":null,"customfield_12310320":null,"customfield_12312024":null,"customfield_12312340":null,"attachment":[],"aggregatetimeestimate":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12312022":null,"customfield_12310921":null,"customfield_12310920":"113065","customfield_12312823":null,"summary":"ERROR Block blk_XXX_1030 already exists in state RBW and thus cannot be created","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":"dfs.support.append=true\n\nCurrent branch-0.21 of hdfs, mapreduce, and common. Here is svn info:\n\nURL: https://svn.apache.org/repos/asf/hadoop/hdfs/branches/branch-0.21\nRepository Root: https://svn.apache.org/repos/asf\nRepository UUID: 13f79535-47bb-0310-9956-ffa450edef68\nRevision: 827883\nNode Kind: directory\nSchedule: normal\nLast Changed Author: szetszwo\nLast Changed Rev: 826906\nLast Changed Date: 2009-10-20 00:16:25 +0000 (Tue, 20 Oct 2009)","customfield_12313520":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768113","id":"12768113","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"body":"So looking in NN log, I see that block 1030 is what block 1029 became:\n\n{code}\n2009-10-21 04:57:02,890 INFO org.apache.hadoop.hdfs.server.namenode.FSNamesystem: updatePipeline(blk_6345892463926159834_1029) successfully to blk_6345892463926159834_1030\n{code}\n\nLooking up at application level, I don't see an exception up at the application level.  Maybe all is working properly... the block goes on to have a long and fruitful life?\n\nHere is rest of log from the NN:\n\n{code}\n2009-10-21 04:57:05,728 WARN org.apache.hadoop.hdfs.server.namenode.FSNamesystem: Inconsistent size for block blk_6345892463926159834_1030 reported from XX.XX.XX.141:51010 current size is 3056128 reported size is 67108864\n2009-10-21 04:57:05,729 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* NameSystem.addStoredBlock: blockMap updated: XX.XX.XX.141:51010 is added to blk_6345892463926159834_1030{blockUCState=UNDER_CONSTRUCTION, primaryNodeIndex=-1, replicas=[ReplicaUnderConstruction[XX.XX.XX.139:51010|RBW], ReplicaUnderConstruction[XX.XX.XX.141:51010|RBW]]} size 67108864\n2009-10-21 04:57:05,733 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* NameSystem.addStoredBlock: blockMap updated: XX.XX.XX.139:51010 is added to blk_6345892463926159834_1030{blockUCState=UNDER_CONSTRUCTION, primaryNodeIndex=-1, replicas=[ReplicaUnderConstruction[XX.XX.XX.139:51010|RBW], ReplicaUnderConstruction[XX.XX.XX.141:51010|RBW]]} size 67108864\n2009-10-21 04:57:07,769 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* ask XX.XX.XX.141:51010 to replicate blk_6345892463926159834_1030 to datanode(s) XX.XX.XX.140:51010\n2009-10-21 05:05:22,268 WARN org.apache.hadoop.hdfs.server.namenode.FSNamesystem: PendingReplicationMonitor timed out block blk_6345892463926159834_1030\n2009-10-21 05:05:27,868 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* ask XX.XX.XX.139:51010 to replicate blk_6345892463926159834_1030 to datanode(s) XX.XX.XX.142:51010\n2009-10-21 05:05:30,299 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* NameSystem.addStoredBlock: blockMap updated: XX.XX.XX.142:51010 is added to blk_6345892463926159834_1030 size 67108864\n2009-10-21 05:06:47,804 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* NameSystem.addToInvalidates: blk_6345892463926159834_1030 to XX.XX.XX.139:51010 XX.XX.XX.141:51010 XX.XX.XX.142:51010 \n2009-10-21 05:06:49,139 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* ask XX.XX.XX.142:51010 to delete  blk_-1883563394128357682_1221 blk_-1418192880479762585_1363 blk_-7630118490185950160_1317 blk_-8001019548793370364_1148 blk_4870116241583532381_1218 blk_2108940364850350519_1082 blk_1036824913411181109_1091 blk_-7589777526384929149_1033 blk_8923577073812832890_1027 blk_-1109307457918706344_1034 blk_-116109986645631967_1219 blk_-1553219148041957509_1367 blk_3763728034862268069_1222 blk_7960880682534006819_1267 blk_-8530634816448964605_1224 blk_666438451332088436_1103 blk_-1943198821321042756_1010 blk_3860462222387154865_1032 blk_-2887612715667758540_1342 blk_2678719195781934773_1348 blk_7531114468370112370_1018 blk_5376641334456236592_1263 blk_5786815585048721793_1025 blk_2870673990810172323_1079 blk_-5877030662574024321_1055 blk_-4584853327269407588_1021 blk_6345892463926159834_1030 blk_8408287293691629994_1268 blk_8109921405484286254_1031 blk_7335139466236556727_1320 blk_1278349007490858566_1272\n2009-10-21 05:06:52,149 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* ask XX.XX.XX.139:51010 to delete  blk_-1883563394128357682_1221 blk_-7630118490185950160_1317 blk_-8001019548793370364_1148 blk_4870116241583532381_1218 blk_2108940364850350519_1082 blk_1036824913411181109_1091 blk_-1919844007905419086_1019 blk_8923577073812832890_1027 blk_-116109986645631967_1219 blk_7960880682534006819_1267 blk_666438451332088436_1103 blk_2067665234645028297_1017 blk_-5406582365187584682_1322 blk_3860462222387154865_1032 blk_-6377718937631289761_1223 blk_2678719195781934773_1348 blk_-2648964128352415897_1023 blk_-8349995959668148332_1051 blk_-4114818907728161248_1035 blk_568068918288377484_1294 blk_-4584853327269407588_1021 blk_6345892463926159834_1030 blk_8408287293691629994_1268 blk_-4335633782362435415_1338 blk_-4179867072599502920_1265 blk_7335139466236556727_1320\n2009-10-21 05:06:52,149 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* ask XX.XX.XX.141:51010 to delete  blk_-1418192880479762585_1363 blk_-7589777526384929149_1033 blk_-1919844007905419086_1019 blk_-1109307457918706344_1034 blk_-1553219148041957509_1367 blk_3763728034862268069_1222 blk_-8530634816448964605_1224 blk_2067665234645028297_1017 blk_-1943198821321042756_1010 blk_-5406582365187584682_1322 blk_-6377718937631289761_1223 blk_-2887612715667758540_1342 blk_-2648964128352415897_1023 blk_7531114468370112370_1018 blk_-8349995959668148332_1051 blk_5376641334456236592_1263 blk_-3674434173543740123_1147 blk_-4114818907728161248_1035 blk_5786815585048721793_1025 blk_2870673990810172323_1079 blk_-5877030662574024321_1055 blk_568068918288377484_1294 blk_6345892463926159834_1030 blk_-4335633782362435415_1338 blk_8109921405484286254_1031 blk_-4179867072599502920_1265 blk_1278349007490858566_1272\n{code}","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"created":"2009-10-21T06:40:36.000+0000","updated":"2009-10-21T06:40:36.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768430","id":"12768430","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hairong","name":"hairong","key":"hairong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hairong Kuang","active":true,"timeZone":"Etc/UTC"},"body":"Thanks Stack for the detailed logs. They are very useful for me to investigate the issue. Was your file's replication factor 3? Were you running your test in a very small cluster?\n\nIt seemed to me this was what happened:\n1. When the block was created, the initial pipeline has datanodes 139, 140, and 141.\n2. 140 failed while the block was being written to.\n3. New pipeline was constructed. Only 139 and 141 remained on the pipeline.\n4. The block completed. 139 & 141 reported to NN the new replica.\n5. NN detetected that the block was under-replicated; therefore scheduled to replicated it to 140.\n6. 140 already has a stale replica of the block; so replication failed.\n7. NN scheduled to replicate it to 142. This replication succeeded.\n\nThe exception was thrown in step 6. I think this is expected.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hairong","name":"hairong","key":"hairong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hairong Kuang","active":true,"timeZone":"Etc/UTC"},"created":"2009-10-21T20:40:00.560+0000","updated":"2009-10-21T20:40:00.560+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768468","id":"12768468","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"body":"@Hairong Thanks for taking a look.  Yes small cluster -- 4 nodes, lots of hbase installs start at about this size -- and yes replication factor was 3.  Story above jibes with me.  Let me close this issue.\n\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"created":"2009-10-21T21:27:50.644+0000","updated":"2009-10-21T21:27:50.644+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768470","id":"12768470","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"body":"Working as designed.  Closing.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"created":"2009-10-21T21:28:09.908+0000","updated":"2009-10-21T21:28:09.908+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768519","id":"12768519","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=szetszwo","name":"szetszwo","key":"szetszwo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=szetszwo&avatarId=23156","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=szetszwo&avatarId=23156","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=szetszwo&avatarId=23156","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=szetszwo&avatarId=23156"},"displayName":"Tsz Wo Nicholas Sze","active":true,"timeZone":"America/Los_Angeles"},"body":"> The exception was thrown in step 6. I think this is expected.\n\nIf it is expected, the log message probably should not be in ERROR level.  WARN or INFO may be enough.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=szetszwo","name":"szetszwo","key":"szetszwo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=szetszwo&avatarId=23156","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=szetszwo&avatarId=23156","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=szetszwo&avatarId=23156","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=szetszwo&avatarId=23156"},"displayName":"Tsz Wo Nicholas Sze","active":true,"timeZone":"America/Los_Angeles"},"created":"2009-10-21T23:34:44.789+0000","updated":"2009-10-21T23:34:44.789+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768533","id":"12768533","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"body":"@Tsz That makes sense...  will I reopen so this issue catches a patch to change log level?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"created":"2009-10-22T00:33:05.784+0000","updated":"2009-10-22T00:33:05.784+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768534","id":"12768534","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=szetszwo","name":"szetszwo","key":"szetszwo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=szetszwo&avatarId=23156","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=szetszwo&avatarId=23156","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=szetszwo&avatarId=23156","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=szetszwo&avatarId=23156"},"displayName":"Tsz Wo Nicholas Sze","active":true,"timeZone":"America/Los_Angeles"},"body":"> ... will I reopen so this issue catches a patch to change log level?\n\nSure.  Let's reopen this for changing the log level.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=szetszwo","name":"szetszwo","key":"szetszwo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=szetszwo&avatarId=23156","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=szetszwo&avatarId=23156","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=szetszwo&avatarId=23156","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=szetszwo&avatarId=23156"},"displayName":"Tsz Wo Nicholas Sze","active":true,"timeZone":"America/Los_Angeles"},"created":"2009-10-22T00:40:57.211+0000","updated":"2009-10-22T00:40:57.211+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768551","id":"12768551","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"body":"Looks like this exception is printed out by the catch in DataNode#run:\n\n{code}\n    while (shouldRun) {\n      try {\n        startDistributedUpgradeIfNeeded();\n        offerService();\n      } catch (Exception ex) {\n        LOG.error(\"Exception: \" + StringUtils.stringifyException(ex));\n        if (shouldRun) {\n          try {\n            Thread.sleep(5000);\n          } catch (InterruptedException ie) {\n          }\n        }\n      }\n{code}\n\nSo, patch would add catch of ReplicaAlreadyExistsException to above try/catch and do a LOG.warn printing out the stacktrace?  Does that sound good?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stack","name":"stack","key":"stack","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"stack","active":true,"timeZone":"America/Los_Angeles"},"created":"2009-10-22T03:20:54.886+0000","updated":"2009-10-22T03:20:54.886+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12768901","id":"12768901","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hairong","name":"hairong","key":"hairong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hairong Kuang","active":true,"timeZone":"Etc/UTC"},"body":"Just in this particular case, the exception is expected. But in most of the cases, this is really an error. I do not think we should change the log level.\n\nBTW, the logging is done at DataXceiver#run() lines 113:\n{noformat}\n    } catch (Throwable t) {\n      LOG.error(datanode.dnRegistration + \":DataXceiver\",t);\n    } finally {\n{noformat}\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hairong","name":"hairong","key":"hairong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hairong Kuang","active":true,"timeZone":"Etc/UTC"},"created":"2009-10-22T21:03:30.473+0000","updated":"2009-10-22T21:03:30.473+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/12769422","id":"12769422","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=szetszwo","name":"szetszwo","key":"szetszwo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=szetszwo&avatarId=23156","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=szetszwo&avatarId=23156","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=szetszwo&avatarId=23156","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=szetszwo&avatarId=23156"},"displayName":"Tsz Wo Nicholas Sze","active":true,"timeZone":"America/Los_Angeles"},"body":"> Just in this particular case, the exception is expected. But in most of the cases, this is really an error. I do not think we should change the log level.\n\nThen, the exception for this particular case should be caught separately.  Logging expected behavior in ERROR will confuse users and ops.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=szetszwo","name":"szetszwo","key":"szetszwo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=szetszwo&avatarId=23156","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=szetszwo&avatarId=23156","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=szetszwo&avatarId=23156","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=szetszwo&avatarId=23156"},"displayName":"Tsz Wo Nicholas Sze","active":true,"timeZone":"America/Los_Angeles"},"created":"2009-10-23T20:37:33.986+0000","updated":"2009-10-23T20:37:33.986+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12438664/comment/14078173","id":"14078173","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=aw","name":"aw","key":"aw","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=aw&avatarId=23681","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=aw&avatarId=23681","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=aw&avatarId=23681","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=aw&avatarId=23681"},"displayName":"Allen Wittenauer","active":true,"timeZone":"America/Tijuana"},"body":"This appears to be fixed by HDFS-6123.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=aw","name":"aw","key":"aw","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=aw&avatarId=23681","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=aw&avatarId=23681","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=aw&avatarId=23681","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=aw&avatarId=23681"},"displayName":"Allen Wittenauer","active":true,"timeZone":"America/Tijuana"},"created":"2014-07-29T19:01:40.223+0000","updated":"2014-07-29T19:01:40.223+0000"}],"maxResults":11,"total":11,"startAt":0},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HDFS-721/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i0jpiv:"}}